# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=15)),
                ('album_name', models.CharField(max_length=20)),
                ('artist', models.CharField(max_length=25)),
                ('downloads', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('music_upload', models.FileField(default=None, upload_to=b'')),
                ('album_pic', models.ImageField(default=None, upload_to=b'')),
            ],
        ),
    ]
